### ISSUE TITLE
Issue in running call command

### ISSUE THREAD

**Issue by TasfiaZahin** [bioinfo-biols/CIRI-long#23]
Hi, I am tring to run CIRI-long call command on some long-reads data from the paper data but getting the following error. Am I missing some library? Please ket me know if you have any idea how to resolve this, it would be very helpful for my research. Thanks in advance!

[Tue 2024-04-16 15:47:48] [INFO ] Step 2.1 - Find circRNAs from CCS reads
[Tue 2024-04-16 16:18:43] [100% ] [##################################################]
[Tue 2024-04-16 16:19:02] [INFO ] Step 2.2 - Recover short CCS reads
Traceback (most recent call last):
  File "/datadisk1/tkz5115/tools/CIRI-long/CIRI-long/venv/bin/CIRI-long", line 33, in <module>
    sys.exit(load_entry_point('CIRI-long==1.1.0', 'console_scripts', 'CIRI-long')())
  File "/datadisk1/tkz5115/tools/CIRI-long/CIRI-long/venv/lib/python3.7/site-packages/CIRI_long/main.py", line 268, in main
    func(args)
  File "/datadisk1/tkz5115/tools/CIRI-long/CIRI-long/venv/lib/python3.7/site-packages/CIRI_long/main.py", line 86, in call
    tmp_cnt = recover_ccs_reads(short_seq, ref_fasta, ss_idx, gtf_idx, intron_idx, is_canonical, out_dir, prefix, threads)
  File "/datadisk1/tkz5115/tools/CIRI-long/CIRI-long/venv/lib/python3.7/site-packages/CIRI_long/find_bsj.py", line 452, in recover_ccs_reads
    from bwapy import BwaAligner
  File "/datadisk1/tkz5115/tools/CIRI-long/CIRI-long/venv/lib/python3.7/site-packages/bwapy/__init__.py", line 3, in <module>
    from bwapy.libbwa import BwaAligner
  File "/datadisk1/tkz5115/tools/CIRI-long/CIRI-long/venv/lib/python3.7/site-packages/bwapy/libbwa.py", line 37, in <module>
    libbwa = get_shared_lib('bwalib')
  File "/datadisk1/tkz5115/tools/CIRI-long/CIRI-long/venv/lib/python3.7/site-packages/bwapy/libbwa.py", line 33, in get_shared_lib
    library = ffi.dlopen(lib_file)
  File "/datadisk1/tkz5115/tools/CIRI-long/CIRI-long/venv/lib/python3.7/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/datadisk1/tkz5115/tools/CIRI-long/CIRI-long/venv/lib/python3.7/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/datadisk1/tkz5115/tools/CIRI-long/CIRI-long/venv/lib/python3.7/site-packages/cffi/api.py", line 828, in _load_backend_lib
    return backend.load_library(path, flags)
OSError: cannot load library '/datadisk1/tkz5115/tools/CIRI-long/CIRI-long/venv/lib/python3.7/site-packages/bwalib.cpython-37m-x86_64-linux-gnu.so': /datadisk1/tkz5115/tools/CIRI-long/CIRI-long/venv/lib/python3.7/site-packages/bwalib.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __log_finite

**Comment by AugustNB** [comment]
I am getting the same exact error, did you ever manage to resolve it?
