### ISSUE TITLE
CIRI-long collapse showing error

### ISSUE THREAD

**Issue by aman21392** [bioinfo-biols/CIRI-long#3]
CIRI-long collapse -i ./test_call/test.lst -o /home/aclab/apps/CIRI-long/test_data/test_collapse/ -r mm10_chr12.fa -a mm10_chr12.gtf -t 70

[Mon 2021-03-15 15:46:07] [INFO ] ----------------- Input paramters ------------------
[Mon 2021-03-15 15:46:07] [INFO ] Input reads: test.lst
[Mon 2021-03-15 15:46:07] [INFO ] Output directory: test_collapse
[Mon 2021-03-15 15:46:07] [INFO ] Multi threads: 70
[Mon 2021-03-15 15:46:07] [INFO ] -------------- Collapse circular reads -------------
[Mon 2021-03-15 15:46:07] [INFO ] Loading pre-built splice site index from: /home/aclab/apps/CIRI-long/test_data/test_collapse/tmp/ss.idx
[Mon 2021-03-15 15:46:08] [INFO ] Step 1 - Clustering candidate circular reads
[Mon 2021-03-15 15:46:08] [INFO ] Circular reads clusters: 213
[Mon 2021-03-15 15:46:09] [0%   ] [..................................................]multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/aclab/apps/pyspoa/pyspoa/lib/python3.6/site-packages/CIRI_long/collapse.py", line 227, in correct_chunk
    ret = correct_cluster(cluster, max_cluster=max_cluster)
  File "/home/aclab/apps/pyspoa/pyspoa/lib/python3.6/site-packages/CIRI_long/collapse.py", line 406, in correct_cluster
    isoforms, circ_len = curate_isoform(circ, curated_exons, cluster_res)
  File "/home/aclab/apps/pyspoa/pyspoa/lib/python3.6/site-packages/CIRI_long/collapse.py", line 691, in curate_isoform
    tmp_isoform, tmp_len = merge_isoforms(circ, curated_exons, tmp_seq, tmp_ids)
  File "/home/aclab/apps/pyspoa/pyspoa/lib/python3.6/site-packages/CIRI_long/collapse.py", line 713, in merge_isoforms
    aligner = Aligner(seq, match=10, mismatch=4, gap_open=8, gap_extend=2)
  File "/home/aclab/apps/pyspoa/pyspoa/lib/python3.6/site-packages/libs/striped_smith_waterman/ssw_wrap.py", line 134, in __init__
    self.set_ref(ref_seq)
  File "/home/aclab/apps/pyspoa/pyspoa/lib/python3.6/site-packages/libs/striped_smith_waterman/ssw_wrap.py", line 167, in set_ref
    self.ref_seq = self._DNA_to_int_mat (ref_seq, self.ref_len)
  File "/home/aclab/apps/pyspoa/pyspoa/lib/python3.6/site-packages/libs/striped_smith_waterman/ssw_wrap.py", line 245, in _DNA_to_int_mat
    value = self.base_to_int[seq[i]]
TypeError: unhashable type: 'list'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aclab/apps/pyspoa/pyspoa/bin/CIRI-long", line 33, in <module>
    sys.exit(load_entry_point('CIRI-long==1.0', 'console_scripts', 'CIRI-long')())
  File "/home/aclab/apps/pyspoa/pyspoa/lib/python3.6/site-packages/CIRI_long/main.py", line 246, in main
    args.func(args)
  File "/home/aclab/apps/pyspoa/pyspoa/lib/python3.6/site-packages/CIRI_long/main.py", line 160, in collapse
    circ_num, corrected_reads = collapse.correct_reads(reads_cluster, ref_fasta, gtf_idx, intron_idx, ss_idx, threads)
  File "/home/aclab/apps/pyspoa/pyspoa/lib/python3.6/site-packages/CIRI_long/collapse.py", line 861, in correct_reads
    tmp_cluster, tmp_num = job.get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: unhashable type: 'list'

Can you please tell me why is it happen

**Comment by Kevinzjy** [comment]
Hi @aman21392, thanks for letting me aware. I've located a bug introduced when I switching from customized spoa cython API to pyspoa package and will upload a fixed version very soon.

**Comment by Kevinzjy** [comment]
Fixed in the latest version v1.0.1

**Comment by aman21392** [comment]
So if I install directly from pip then it automatically installs the latest version or i have to download it from Github.
Thanks

**Comment by Kevinzjy** [comment]
I've also updated CIRI-long on pypi.org, so `pip install CIRI-long --upgrade` should work fine.

**Comment by aman21392** [comment]
OK thanks

**Comment by aman21392** [comment]
Hi, I just want to know that after running CIRI-long test data how much circRNA we get. I got 157 circRNA, so is it the correct ones, when you run test data.
Thanks in advance

**Comment by Kevinzjy** [comment]
> Hi, I just want to know that after running CIRI-long test data how much circRNA we get. I got 157 circRNA, so is it the correct ones, when you run test data.
> Thanks in advance

Yes, it's the correct number in the test dataset.

**Comment by aman21392** [comment]
Thanks a lot.

**Comment by aman21392** [comment]
I just want to know you used a 30 nanopore dataset so how many circRNA found in each dataset. I want to know because I also run CIRI-long on those datasets. So can you please provide the circRNA no. in each dataset and how many are present in circAtlas in each datasets.
Thanks in advance

**Comment by Kevinzjy** [comment]
You need to run the "collapse" command using all results from 32 libraries to get the final results, and use the expression matrix as final results. I haven't count the overlap of circAtlas in each dataset, but if you generated the matrix successfully, the results should be the same as that in our manuscript.

**Comment by aman21392** [comment]
OK thanks, There is no human data only just mouse nanopore data. So all primers for validation in the paper have come from the mouse genome only.
